import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Layout from "@/layout/Layout";
import Navbar from "@/components/navbar/Navbar";
import { ClerkLoaded, ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import LoadingPage from "@/components/loading/LoadingPage";
import TrpcProvider from "@/providers/TrpcProvider";

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} max-w-screen relative h-screen w-full bg-background antialiased`}
        >
          <ClerkLoading>
            <LoadingPage />
          </ClerkLoading>

          <ClerkLoaded>
            <TrpcProvider>
              <Navbar />
              <Layout>{children}</Layout>
            </TrpcProvider>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
