import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Layout from "@/layout/Layout";
import Navbar from "@/components/navbar/Navbar";
import { ClerkLoading, ClerkProvider } from "@clerk/nextjs";
import LoadingPage from "@/components/loading/LoadingPage";

export const metadata: Metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${poppins.variable} antialiased relative bg-background h-screen max-w-screen w-full`}
        >
          <ClerkLoading>
            <LoadingPage />
          </ClerkLoading>
          <Navbar />
          <Layout>{children}</Layout>
        </body>
      </html>
    </ClerkProvider>
  );
}
